### ISSUE TITLE
Enhance reducers/app and extends it in Opla

### ISSUE THREAD

**Issue by JulienUsson** [Zoapp/front#39]

**Comment by willdurand** [comment]
I would suggest to `export` the second parameter in `createReducer` here: https://github.com/Zoapp/front/blob/6ce4247902b962a88be8589e562b209e94119cc5/src/shared/reducers/app.js#L27. That way, we can reuse it in Opla/front. Let's name it... `handlers`.

**Comment by JulienUsson** [comment]
it's exactly what i have done :)
