### ISSUE TITLE
Make App title more usefull

### ISSUE THREAD

**Issue by mikbry** [Zoapp/front#69]
### Now
We only display app name in toolbar's title

### Todo
Add more informations in config.js or for zoapp-front src/client/index.js
```
const xxx = {
  name: "Zoapp",
  subname: "CE",
  instance: {
    name: "QA Instance",
    color: "#f05545",
    description: "A warning message",
  },
```
Will be displayed as :
![screen shot 2018-05-29 at 10 04 03](https://user-images.githubusercontent.com/395718/40645805-b3d9b412-6327-11e8-9218-07b049fd55cd.png)

instance.description will display a permanent warning in footer.

All these parameters (except name) could be bypassed using env vars, same for version could be taken from package.json.

**Comment by lodelestra** [comment]
### Implementation note
IMO, this info should also be added in app reducer, like app name, version and title already are.
<img width="307" alt="screen shot 2018-05-29 at 10 12 32" src="https://user-images.githubusercontent.com/10141712/40646372-3e2a8028-6329-11e8-9e13-fcbc8323a511.png">

**Comment by mikbry** [comment]
If you add this parameters to config/app object, they will be available in app reducer.
