### ISSUE TITLE
Tabbar index not reset when displaying new screen

### ISSUE THREAD

**Issue by mikbry** [Zoapp/front#74]
### When
- Signin
- Select tab2 in dashboard
- select admin
- advanced is selected
- but Users are displayed

### Should be
- users tab selected

**Comment by lodelestra** [comment]
I don't find a second tab in dashboard. Is it conditional to the number of bots ?

**Comment by mikbry** [comment]
@lodelestra we talk about Zoapp not Opla the dashboard is not the same ;-)

**Comment by lodelestra** [comment]
My bad! thanks

**Comment by mikbry** [comment]
Should be fixed in latest release 0.24.0. Migrating to React 16.4 and using Zrmc tabbar with derivatedState.
