### ISSUE TITLE
Theming : dark drawer and white toolbar

### ISSUE THREAD

**Issue by mikbry** [Zoapp/front#78]
In app properties add to design object a toolbar.theme :
```
  design: {
    minTitleName: true,
    toolbar: {
      theme: "white",
    },
    drawer: {
      type: "persistent",
      themeDark: true,
```
Also we need to implement themeDark for drawer.

It should look like:
![screen shot 2018-06-06 at 10 46 19](https://user-images.githubusercontent.com/395718/41027531-90538698-6977-11e8-8133-577a63f8c4c8.png)

**Comment by lodelestra** [comment]
Closed by #81
