### ISSUE TITLE
Temporary Drawer : close on item select

### ISSUE THREAD

**Issue by mikbry** [Zoapp/front#80]
Change drawer.type to temporary
```
  design: {
    minTitleName: true,
    drawer: {
      type: "temporary",
      themeDark: true,
      renderFooter: (props) => <DrawerFooter {...props} />,
    },
  },
```
Select an item in drawer. 
It should close the drawer.

Also there is no animation to open/close the Drawer see :
https://github.com/Zoapp/react-materialcomponents/issues/1

**Comment by lodelestra** [comment]
closed by #83
